apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: app:v0.0.2    # 改为你的实际镜像名和标签
        imagePullPolicy: Never   # 添加这个确保使用本地镜像
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-test-app"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "test123456"
        - name: DB_NAME
          value: "testdb"
        - name: MINIO_ENDPOINT
          value: "http://blob-test-app:9000"
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"